project_id = "bzugdsinavlttuosoxos"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]

[database]
enabled = true

[storage]
enabled = true