// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzugdsinavlttuosoxos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6dWdkc2luYXZsdHR1b3NveG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzA2NzksImV4cCI6MjA2OTgwNjY3OX0.Ke2OUN4hCzV38yN16rgd2OAeZ8mej4J34XUUGJWSS5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});